<a href="https://colab.research.google.com/github/TAGARA-TECH/Pandas_transformacion_y_manipulacion_de_datos/blob/main/Pandas_Tratamiento_Manipulacion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import json

# Cargar los datos originales
datos = pd.read_json('/content/datos_hosting.json')

# Normalizar la columna 'info_inmuebles'
try:
    info_inmuebles_aplanado = pd.json_normalize(datos['info_inmuebles'])
except Exception as e:
    print(f"No se pudo normalizar la columna 'info_inmuebles': {e}")
    info_inmuebles_aplanado = pd.DataFrame() # Crea un DataFrame vacío si falla

# Concatenar el DataFrame original (sin 'info_inmuebles') con el normalizado
datos_aplanado = datos.drop(columns=['info_inmuebles'], errors='ignore').copy()

if not info_inmuebles_aplanado.empty:
    datos_aplanado = pd.concat([datos_aplanado, info_inmuebles_aplanado], axis=1)
else:
    print("La normalización de 'info_inmuebles' falló o resultó vacía.")

# --- Procesar las columnas que todavía contienen listas ---

# Función para procesar columnas de descripción (tomar el primer elemento)
def get_first_element(lista):
    if isinstance(lista, list) and lista:
        return lista[0]
    return None # O alguna otra representación para valores faltantes/vacíos

# Aplicar la función a las columnas de descripción
for col in ['descripcion_local', 'descripcion_vecindad']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_element)

# Función para procesar columnas de cantidad (tomar el primer elemento)
def get_first_number(lista):
    if isinstance(lista, list) and lista:
        try:
            # Intenta convertir a número si es posible
            return float(lista[0])
        except (ValueError, TypeError):
            return None # Retorna None si no se puede convertir a número
    return None

# Aplicar la función a las columnas de cantidad
for col in ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']:
     if col in datos_aplanado.columns:
        # Intenta convertir los elementos de la lista a string antes de aplicar get_first_number
        datos_aplanado[col] = datos_aplanado[col].apply(lambda x: [str(item) for item in x] if isinstance(x, list) else x)
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_number)


# Procesar 'modelo_cama' (tomar el primer elemento)
if 'modelo_cama' in datos_aplanado.columns:
    datos_aplanado['modelo_cama'] = datos_aplanado['modelo_cama'].apply(get_first_element)

# Procesar 'comodidades' (extraer las comodidades de la lista)
# Esto es más complejo y dependerá del formato exacto dentro de la lista.
# Aquí un ejemplo simple que intenta extraer elementos si son strings.
def extract_amenities(lista):
    if isinstance(lista, list):
        # Une los elementos de la lista con una coma (ajusta si necesitas algo diferente)
        return ', '.join([str(item).strip() for item in lista if isinstance(item, (str, dict, list))])
    return None

if 'comodidades' in datos_aplanado.columns:
     datos_aplanado['comodidades'] = datos_aplanado['comodidades'].apply(extract_amenities)


# Función para limpiar y convertir columnas de precio/cuota a numérico
def clean_currency(lista):
    if isinstance(lista, list) and lista:
        # Tomar el primer elemento, quitar '$' y ',' y convertir a float
        try:
            value_str = str(lista[0]).replace('$', '').replace(',', '').strip()
            if value_str: # Asegurarse de que no esté vacío después de limpiar
                 return float(value_str)
            return 0.0 # O np.nan si prefieres representar valores faltantes
        except (ValueError, TypeError):
             return 0.0 # Retornar 0.0 o np.nan si falla la conversión
    return 0.0 # Retornar 0.0 o np.nan para listas vacías o no listas

# Aplicar la función a las columnas de precio/cuota
for col in ['cuota_deposito', 'cuota_limpieza', 'precio']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(clean_currency)

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado
print(datos_aplanado.info())

  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  This clean and comfortable one bedroom sits ri...
1  Welcome to the heart of the 'Ballard Brewery D...
2  New modern house built in 2013.  Spectacular s...
3  Our NW style home is 3200+ sq ft with 3 levels...
4  Perfect for groups. 2 bedrooms, full bathrooms...

                                descripcion_vecindad  cantidad_baños  \
0  Lower Queen Anne is near the Seattle Center (s...             1.0
1                                                 --             2.0
2  Upper Queen Anne is a charming neighborhood fu...             4.0
3  The Views from our top floor!  Wallingford has...             3.0
4  Safeway grocery store within walking distance....             2.0

   cantidad_cuartos  cantidad_camas modelo_cama  \
0               1.0             1.0    Real Bed
1               3.0             5.0    Real Bed
2               5.0             7.0    Real Bed
3               6.0             6.0    Real Bed
4               2.0             3.0    Real Bed

                                         comodidades  cuota_deposito  \
0  {Internet,"Wireless Internet",Kitchen,"Free Pa...             0.0
1  {TV,Internet,"Wireless Internet",Kitchen,"Free...           500.0
2  {TV,"Cable TV",Internet,"Wireless Internet","A...          1000.0
3  {Internet,"Wireless Internet",Kitchen,"Free Pa...           500.0
4  {TV,Internet,"Wireless Internet",Kitchen,"Free...           300.0

   cuota_limpieza  precio
0             0.0   110.0
1           125.0   350.0
2           300.0   975.0
3           225.0   490.0
4            40.0   200.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     float64
 6   cantidad_cuartos      70 non-null     float64
 7   cantidad_camas        70 non-null     float64
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     float64
 11  cuota_limpieza        70 non-null     float64
 12  precio                70 non-null     float64
dtypes: float64(6), object(7)
memory usage: 7.2+ KB
None

In [ ]:
import pandas as pd
import json

# Cargar los datos originales
datos = pd.read_json('/content/datos_hosting.json')

# Normalizar la columna 'info_inmuebles'
try:
    info_inmuebles_aplanado = pd.json_normalize(datos['info_inmuebles'])
except Exception as e:
    print(f"No se pudo normalizar la columna 'info_inmuebles': {e}")
    info_inmuebles_aplanado = pd.DataFrame() # Crea un DataFrame vacío si falla

# Concatenar el DataFrame original (sin 'info_inmuebles') con el normalizado
datos_aplanado = datos.drop(columns=['info_inmuebles'], errors='ignore').copy()

if not info_inmuebles_aplanado.empty:
    datos_aplanado = pd.concat([datos_aplanado, info_inmuebles_aplanado], axis=1)
else:
    print("La normalización de 'info_inmuebles' falló o resultó vacía.")

# --- Procesar las columnas que todavía contienen listas ---

# Función para procesar columnas de descripción (tomar el primer elemento)
def get_first_element(lista):
    if isinstance(lista, list) and lista:
        return lista[0]
    return None # O alguna otra representación para valores faltantes/vacíos

# Aplicar la función a las columnas de descripción
for col in ['descripcion_local', 'descripcion_vecindad']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_element)

# Función para procesar columnas de cantidad (tomar el primer elemento)
def get_first_number(lista):
    if isinstance(lista, list) and lista:
        try:
            # Intenta convertir a número si es posible
            return float(lista[0])
        except (ValueError, TypeError):
            return None # Retorna None si no se puede convertir a número
    return None

# Aplicar la función a las columnas de cantidad
for col in ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']:
     if col in datos_aplanado.columns:
        # Intenta convertir los elementos de la lista a string antes de aplicar get_first_number
        datos_aplanado[col] = datos_aplanado[col].apply(lambda x: [str(item) for item in x] if isinstance(x, list) else x)
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_number)


# Procesar 'modelo_cama' (tomar el primer elemento)
if 'modelo_cama' in datos_aplanado.columns:
    datos_aplanado['modelo_cama'] = datos_aplanado['modelo_cama'].apply(get_first_element)

# Procesar 'comodidades' (extraer las comodidades de la lista)
# Esto es más complejo y dependerá del formato exacto dentro de la lista.
# Aquí un ejemplo simple que intenta extraer elementos si son strings.
def extract_amenities(lista):
    if isinstance(lista, list):
        # Une los elementos de la lista con una coma (ajusta si necesitas algo diferente)
        return ', '.join([str(item).strip() for item in lista if isinstance(item, (str, dict, list))])
    return None

if 'comodidades' in datos_aplanado.columns:
     datos_aplanado['comodidades'] = datos_aplanado['comodidades'].apply(extract_amenities)


# Función para limpiar y convertir columnas de precio/cuota a numérico
def clean_currency(lista):
    if isinstance(lista, list) and lista:
        # Tomar el primer elemento, quitar '$' y ',' y convertir a float
        try:
            value_str = str(lista[0]).replace('$', '').replace(',', '').strip()
            if value_str: # Asegurarse de que no esté vacío después de limpiar
                 return float(value_str)
            return 0.0 # O np.nan si prefieres representar valores faltantes
        except (ValueError, TypeError):
             return 0.0 # Retornar 0.0 o np.nan si falla la conversión
    return 0.0 # Retornar 0.0 o np.nan para listas vacías o no listas

# Aplicar la función a las columnas de precio/cuota
for col in ['cuota_deposito', 'cuota_limpieza', 'precio']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(clean_currency)

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado
print(datos_aplanado.info())

  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  This clean and comfortable one bedroom sits ri...
1  Welcome to the heart of the 'Ballard Brewery D...
2  New modern house built in 2013.  Spectacular s...
3  Our NW style home is 3200+ sq ft with 3 levels...
4  Perfect for groups. 2 bedrooms, full bathrooms...

                                descripcion_vecindad  cantidad_baños  \
0  Lower Queen Anne is near the Seattle Center (s...             1.0
1                                                 --             2.0
2  Upper Queen Anne is a charming neighborhood fu...             4.0
3  The Views from our top floor!  Wallingford has...             3.0
4  Safeway grocery store within walking distance....             2.0

   cantidad_cuartos  cantidad_camas modelo_cama  \
0               1.0             1.0    Real Bed
1               3.0             5.0    Real Bed
2               5.0             7.0    Real Bed
3               6.0             6.0    Real Bed
4               2.0             3.0    Real Bed

                                         comodidades  cuota_deposito  \
0  {Internet,"Wireless Internet",Kitchen,"Free Pa...             0.0
1  {TV,Internet,"Wireless Internet",Kitchen,"Free...           500.0
2  {TV,"Cable TV",Internet,"Wireless Internet","A...          1000.0
3  {Internet,"Wireless Internet",Kitchen,"Free Pa...           500.0
4  {TV,Internet,"Wireless Internet",Kitchen,"Free...           300.0

   cuota_limpieza  precio
0             0.0   110.0
1           125.0   350.0
2           300.0   975.0
3           225.0   490.0
4            40.0   200.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     float64
 6   cantidad_cuartos      70 non-null     float64
 7   cantidad_camas        70 non-null     float64
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     float64
 11  cuota_limpieza        70 non-null     float64
 12  precio                70 non-null     float64
dtypes: float64(6), object(7)
memory usage: 7.2+ KB
None

In [ ]:

# Normalizar la columna 'info_inmuebles'
try:
    info_inmuebles_aplanado = pd.json_normalize(datos['info_inmuebles'])
except Exception as e:
    print(f"No se pudo normalizar la columna 'info_inmuebles': {e}")
    info_inmuebles_aplanado = pd.DataFrame() # Crea un DataFrame vacío si falla

# Concatenar el DataFrame original (sin 'info_inmuebles') con el normalizado
datos_aplanado = datos.drop(columns=['info_inmuebles'], errors='ignore').copy()

if not info_inmuebles_aplanado.empty:
    datos_aplanado = pd.concat([datos_aplanado, info_inmuebles_aplanado], axis=1)
else:
    print("La normalización de 'info_inmuebles' falló o resultó vacía.")

# --- Procesar las columnas que todavía contienen listas ---

# Función para procesar columnas de descripción (tomar el primer elemento)
def get_first_element(lista):
    if isinstance(lista, list) and lista:
        return lista[0]
    return None # O alguna otra representación para valores faltantes/vacíos

# Aplicar la función a las columnas de descripción
for col in ['descripcion_local', 'descripcion_vecindad']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_element)

# Función para procesar columnas de cantidad (tomar el primer elemento)
def get_first_number(lista):
    if isinstance(lista, list) and lista:
        try:
            # Intenta convertir a número si es posible
            return float(lista[0])
        except (ValueError, TypeError):
            return None # Retorna None si no se puede convertir a número
    return None

# Aplicar la función a las columnas de cantidad
for col in ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']:
     if col in datos_aplanado.columns:
        # Intenta convertir los elementos de la lista a string antes de aplicar get_first_number
        datos_aplanado[col] = datos_aplanado[col].apply(lambda x: [str(item) for item in x] if isinstance(x, list) else x)
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_number)


# Procesar 'modelo_cama' (tomar el primer elemento)
if 'modelo_cama' in datos_aplanado.columns:
    datos_aplanado['modelo_cama'] = datos_aplanado['modelo_cama'].apply(get_first_element)

# Procesar 'comodidades' (extraer las comodidades de la lista)
# Esto es más complejo y dependerá del formato exacto dentro de la lista.
# Aquí un ejemplo simple que intenta extraer elementos si son strings.
def extract_amenities(lista):
    if isinstance(lista, list):
        # Une los elementos de la lista con una coma (ajusta si necesitas algo diferente)
        return ', '.join([str(item).strip() for item in lista if isinstance(item, (str, dict, list))])
    return None

if 'comodidades' in datos_aplanado.columns:
     datos_aplanado['comodidades'] = datos_aplanado['comodidades'].apply(extract_amenities)


# Función para limpiar y convertir columnas de precio/cuota a numérico
def clean_currency(lista):
    if isinstance(lista, list) and lista:
        # Tomar el primer elemento, quitar '$' y ',' y convertir a float
        try:
            value_str = str(lista[0]).replace('$', '').replace(',', '').strip()
            if value_str: # Asegurarse de que no esté vacío después de limpiar
                 return float(value_str)
            return 0.0 # O np.nan si prefieres representar valores faltantes
        except (ValueError, TypeError):
             return 0.0 # Retornar 0.0 o np.nan si falla la conversión
    return 0.0 # Retornar 0.0 o np.nan para listas vacías o no listas

# Aplicar la función a las columnas de precio/cuota
for col in ['cuota_deposito', 'cuota_limpieza', 'precio']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(clean_currency)

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado
print(datos_aplanado.info())

  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  This clean and comfortable one bedroom sits ri...
1  Welcome to the heart of the 'Ballard Brewery D...
2  New modern house built in 2013.  Spectacular s...
3  Our NW style home is 3200+ sq ft with 3 levels...
4  Perfect for groups. 2 bedrooms, full bathrooms...

                                descripcion_vecindad  cantidad_baños  \
0  Lower Queen Anne is near the Seattle Center (s...             1.0
1                                                 --             2.0
2  Upper Queen Anne is a charming neighborhood fu...             4.0
3  The Views from our top floor!  Wallingford has...             3.0
4  Safeway grocery store within walking distance....             2.0

   cantidad_cuartos  cantidad_camas modelo_cama  \
0               1.0             1.0    Real Bed
1               3.0             5.0    Real Bed
2               5.0             7.0    Real Bed
3               6.0             6.0    Real Bed
4               2.0             3.0    Real Bed

                                         comodidades  cuota_deposito  \
0  {Internet,"Wireless Internet",Kitchen,"Free Pa...             0.0
1  {TV,Internet,"Wireless Internet",Kitchen,"Free...           500.0
2  {TV,"Cable TV",Internet,"Wireless Internet","A...          1000.0
3  {Internet,"Wireless Internet",Kitchen,"Free Pa...           500.0
4  {TV,Internet,"Wireless Internet",Kitchen,"Free...           300.0

   cuota_limpieza  precio
0             0.0   110.0
1           125.0   350.0
2           300.0   975.0
3           225.0   490.0
4            40.0   200.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     float64
 6   cantidad_cuartos      70 non-null     float64
 7   cantidad_camas        70 non-null     float64
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     float64
 11  cuota_limpieza        70 non-null     float64
 12  precio                70 non-null     float64
dtypes: float64(6), object(7)
memory usage: 7.2+ KB
None

In [ ]:
print(datos_aplanado.shape)

(70, 13)

In [ ]:
print(datos_aplanado.columns.tolist())

['evaluacion_general', 'experiencia_local', 'max_hospedes', 'descripcion_local', 'descripcion_vecindad', 'cantidad_baños', 'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'comodidades', 'cuota_deposito', 'cuota_limpieza', 'precio']

In [ ]:
print(datos_aplanado.shape)

(70, 13)

#**PROBLEMA DE NEGOCIO**


---

Se trata de un algoritmo capaz de analizar las características de una propiedad -como comodidades, tamaño, ocupación del espacio en un período determinado- y sugerir al anfitrión un precio a cobrar por tarifas diarias que garantice ganancias en momentos de alta demanda.

#**1. Entendiendo el Problema**


---

In [ ]:
#datos = pd.read_json('/content/datos_hosting.json')
#datos.head()

In [ ]:
datos = pd.json_normalize(datos['info_inmuebles'])
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [ ]:
# Explorar las columnas y tipos de datos
print(datos.info())

# Mostrar estadísticas descriptivas
print(datos.describe())

# Mostrar las primeras filas del dataframe
print(datos.head())

# Mostrar los nombres de las columnas
print(datos.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB
None
       evaluacion_general experiencia_local max_hospedes  \
count                  70                70           70
unique                  9                 1           15
top                  10.0                --            2
freq                   14                70            9

                                        descripcion_local  \
count                                                  70
unique                                                 70
top     [This clean and comfortable one bedroom sits r...
freq                                                    1

       descripcion_vecindad cantidad_baños cantidad_cuartos cantidad_camas  \
count                    70             70               70             70
unique                   66             57               60             58
top                    [--]            [1]              [5]            [1]
freq                      5              6                3              4

       modelo_cama                                        comodidades  \
count           70                                                 70
unique          38                                                 70
top     [Real Bed]  [{Internet,"Wireless Internet",Kitchen,"Free P...
freq            14                                                  1

       cuota_deposito cuota_limpieza    precio
count              70             70        70
unique             67             66        69
top       [$1,000.00]       [$50.00]  [$95.00]
freq                2              2         2
  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]
Index(['evaluacion_general', 'experiencia_local', 'max_hospedes',
       'descripcion_local', 'descripcion_vecindad', 'cantidad_baños',
       'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'comodidades',
       'cuota_deposito', 'cuota_limpieza', 'precio'],
      dtype='object')

In [ ]:
# Exploración inicial

print('dtypes',datos.dtypes)

# Exploración inicial

print('dtypes',datos.dtypes)

print('isnull().sum()', datos.isnull().sum())

print('.describe(include=\'all\')', datos.describe(include='all'))

print('.head()', datos.head())

dtypes evaluacion_general      object
experiencia_local       object
max_hospedes            object
descripcion_local       object
descripcion_vecindad    object
cantidad_baños          object
cantidad_cuartos        object
cantidad_camas          object
modelo_cama             object
comodidades             object
cuota_deposito          object
cuota_limpieza          object
precio                  object
dtype: object
dtypes evaluacion_general      object
experiencia_local       object
max_hospedes            object
descripcion_local       object
descripcion_vecindad    object
cantidad_baños          object
cantidad_cuartos        object
cantidad_camas          object
modelo_cama             object
comodidades             object
cuota_deposito          object
cuota_limpieza          object
precio                  object
dtype: object
isnull().sum() evaluacion_general      0
experiencia_local       0
max_hospedes            0
descripcion_local       0
descripcion_vecindad    0
cantidad_baños          0
cantidad_cuartos        0
cantidad_camas          0
modelo_cama             0
comodidades             0
cuota_deposito          0
cuota_limpieza          0
precio                  0
dtype: int64
.describe(include='all')        evaluacion_general experiencia_local max_hospedes  \
count                  70                70           70
unique                  9                 1           15
top                  10.0                --            2
freq                   14                70            9

                                        descripcion_local  \
count                                                  70
unique                                                 70
top     [This clean and comfortable one bedroom sits r...
freq                                                    1

       descripcion_vecindad cantidad_baños cantidad_cuartos cantidad_camas  \
count                    70             70               70             70
unique                   66             57               60             58
top                    [--]            [1]              [5]            [1]
freq                      5              6                3              4

       modelo_cama                                        comodidades  \
count           70                                                 70
unique          38                                                 70
top     [Real Bed]  [{Internet,"Wireless Internet",Kitchen,"Free P...
freq            14                                                  1

       cuota_deposito cuota_limpieza    precio
count              70             70        70
unique             67             66        69
top       [$1,000.00]       [$50.00]  [$95.00]
freq                2              2         2
.head()   evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]

In [ ]:
# Explorar las columnas y tipos de datos del dataframe original
print(datos.info())

# Mostrar estadísticas descriptivas del dataframe original
print(datos.describe())

# Mostrar las primeras filas del dataframe original
print(datos.head())

# Mostrar los nombres de las columnas del dataframe original
print(datos.columns)

# Assuming 'info_inmuebles_aplanado' was created in a previous cell
# If not, you will need to run the cell that normalizes 'info_inmuebles'
# and assigns it to 'info_inmuebles_aplanado' before this cell.
pd.concat([datos, info_inmuebles_aplanado], axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB
None
       evaluacion_general experiencia_local max_hospedes  \
count                  70                70           70
unique                  9                 1           15
top                  10.0                --            2
freq                   14                70            9

                                        descripcion_local  \
count                                                  70
unique                                                 70
top     [This clean and comfortable one bedroom sits r...
freq                                                    1

       descripcion_vecindad cantidad_baños cantidad_cuartos cantidad_camas  \
count                    70             70               70             70
unique                   66             57               60             58
top                    [--]            [1]              [5]            [1]
freq                      5              6                3              4

       modelo_cama                                        comodidades  \
count           70                                                 70
unique          38                                                 70
top     [Real Bed]  [{Internet,"Wireless Internet",Kitchen,"Free P...
freq            14                                                  1

       cuota_deposito cuota_limpieza    precio
count              70             70        70
unique             67             66        69
top       [$1,000.00]       [$50.00]  [$95.00]
freq                2              2         2
  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]
Index(['evaluacion_general', 'experiencia_local', 'max_hospedes',
       'descripcion_local', 'descripcion_vecindad', 'cantidad_baños',
       'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'comodidades',
       'cuota_deposito', 'cuota_limpieza', 'precio'],
      dtype='object')

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,...,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...",...,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...",...,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...",...,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...",...,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...",...,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...",...,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...",...,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...",...,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...",...,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...",...,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

In [ ]:
# Explorar las columnas y tipos de datos del dataframe original
print(datos.info())

# Mostrar estadísticas descriptivas del dataframe original
print(datos.describe())

# Mostrar las primeras filas del dataframe original
print(datos.head())

# Mostrar los nombres de las columnas del dataframe original
print(datos.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB
None
       evaluacion_general experiencia_local max_hospedes  \
count                  70                70           70
unique                  9                 1           15
top                  10.0                --            2
freq                   14                70            9

                                        descripcion_local  \
count                                                  70
unique                                                 70
top     [This clean and comfortable one bedroom sits r...
freq                                                    1

       descripcion_vecindad cantidad_baños cantidad_cuartos cantidad_camas  \
count                    70             70               70             70
unique                   66             57               60             58
top                    [--]            [1]              [5]            [1]
freq                      5              6                3              4

       modelo_cama                                        comodidades  \
count           70                                                 70
unique          38                                                 70
top     [Real Bed]  [{Internet,"Wireless Internet",Kitchen,"Free P...
freq            14                                                  1

       cuota_deposito cuota_limpieza    precio
count              70             70        70
unique             67             66        69
top       [$1,000.00]       [$50.00]  [$95.00]
freq                2              2         2
  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]
Index(['evaluacion_general', 'experiencia_local', 'max_hospedes',
       'descripcion_local', 'descripcion_vecindad', 'cantidad_baños',
       'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'comodidades',
       'cuota_deposito', 'cuota_limpieza', 'precio'],
      dtype='object')

In [ ]:
# Exploración inicial del dataframe original

print('dtypes',datos.dtypes)

print('isnull().sum()', datos.isnull().sum())

print('.describe(include=\'all\')', datos.describe(include='all'))

print('.head()', datos.head())

dtypes evaluacion_general      object
experiencia_local       object
max_hospedes            object
descripcion_local       object
descripcion_vecindad    object
cantidad_baños          object
cantidad_cuartos        object
cantidad_camas          object
modelo_cama             object
comodidades             object
cuota_deposito          object
cuota_limpieza          object
precio                  object
dtype: object
isnull().sum() evaluacion_general      0
experiencia_local       0
max_hospedes            0
descripcion_local       0
descripcion_vecindad    0
cantidad_baños          0
cantidad_cuartos        0
cantidad_camas          0
modelo_cama             0
comodidades             0
cuota_deposito          0
cuota_limpieza          0
precio                  0
dtype: int64
.describe(include='all')        evaluacion_general experiencia_local max_hospedes  \
count                  70                70           70
unique                  9                 1           15
top                  10.0                --            2
freq                   14                70            9

                                        descripcion_local  \
count                                                  70
unique                                                 70
top     [This clean and comfortable one bedroom sits r...
freq                                                    1

       descripcion_vecindad cantidad_baños cantidad_cuartos cantidad_camas  \
count                    70             70               70             70
unique                   66             57               60             58
top                    [--]            [1]              [5]            [1]
freq                      5              6                3              4

       modelo_cama                                        comodidades  \
count           70                                                 70
unique          38                                                 70
top     [Real Bed]  [{Internet,"Wireless Internet",Kitchen,"Free P...
freq            14                                                  1

       cuota_deposito cuota_limpieza    precio
count              70             70        70
unique             67             66        69
top       [$1,000.00]       [$50.00]  [$95.00]
freq                2              2         2
.head()   evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]

In [ ]:
import pandas as pd

# Cargar los datos originales
datos = pd.read_json('/content/datos_hosting.json')

# Identificar las columnas que contienen datos anidados que deseas normalizar
# Asegúrate de que estos nombres de columnas existen en tu DataFrame 'datos'
columnas_anidadas = ['info_inmuebles', 'detalles_adicionales'] # Agrega aquí otras columnas anidadas si las hay

# Crear una lista para almacenar los DataFrames normalizados
dfs_normalizados = []

# Iterar sobre las columnas anidadas y normalizarlas
for columna in columnas_anidadas:
    if columna in datos.columns:
        try:
            # Normalizar la columna anidada
            df_normalizado = pd.json_normalize(datos[columna])
            # Agregar el DataFrame normalizado a la lista
            dfs_normalizados.append(df_normalizado)
            # Opcional: Puedes renombrar las columnas normalizadas si hay nombres duplicados
            # Ejemplo: df_normalizado.columns = [f'{columna}_{c}' for c in df_normalizado.columns]
        except Exception as e:
            print(f"No se pudo normalizar la columna '{columna}': {e}")
    else:
        print(f"La columna '{columna}' no se encuentra en el DataFrame original.")

# Crear una copia del DataFrame original y eliminar las columnas anidadas
datos_aplanado = datos.drop(columns=columnas_anidadas, errors='ignore').copy()

# Concatenar el DataFrame original (sin columnas anidadas) con los DataFrames normalizados
# Asegúrate de que los índices son consistentes para la concatenación axis=1
if dfs_normalizados: # Solo concatenar si hay DataFrames normalizados
    datos_aplanado = pd.concat([datos_aplanado] + dfs_normalizados, axis=1)
else:
    print("No se normalizó ninguna columna. El DataFrame aplanado es el original sin las columnas especificadas.")

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado para ver las nuevas columnas
print(datos_aplanado.info())

La columna 'detalles_adicionales' no se encuentra en el DataFrame original.
  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB
None

In [ ]:
datos_aplanado.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [ ]:
import pandas as pd

# Cargar los datos originales
datos = pd.read_json('/content/datos_hosting.json')

# Lista para almacenar los DataFrames normalizados
dfs_normalizados = []

# Iterar sobre las columnas que potencialmente contienen datos anidados
# Puedes ajustar esta lista según la estructura real de tu JSON
columnas_anidadas = ['info_inmuebles'] # Inicialmente, solo normalizamos 'info_inmuebles'

for columna in columnas_anidadas:
    if columna in datos.columns:
        try:
            # Normalizar la columna anidada
            df_normalizado = pd.json_normalize(datos[columna])
            # Agregar el DataFrame normalizado a la lista
            dfs_normalizados.append(df_normalizado)
        except Exception as e:
            print(f"No se pudo normalizar la columna '{columna}': {e}")
    else:
        print(f"La columna '{columna}' no se encuentra en el DataFrame original.")

# Crear una copia del DataFrame original y eliminar las columnas anidadas que se normalizaron
datos_aplanado = datos.drop(columns=columnas_anidadas, errors='ignore').copy()

# Concatenar el DataFrame original (sin columnas anidadas) con los DataFrames normalizados
# Asegúrate de que los índices son consistentes para la concatenación axis=1
if dfs_normalizados:
    # Si hay DataFrames normalizados, concatenarlos
    datos_aplanado = pd.concat([datos_aplanado] + dfs_normalizados, axis=1)
else:
    print("No se normalizó ninguna columna. El DataFrame aplanado es el original sin las columnas especificadas.")

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado para ver las nuevas columnas
print(datos_aplanado.info())

  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  [This clean and comfortable one bedroom sits r...
1  [Welcome to the heart of the 'Ballard Brewery ...
2  [New modern house built in 2013.  Spectacular ...
3  [Our NW style home is 3200+ sq ft with 3 level...
4  [Perfect for groups. 2 bedrooms, full bathroom...

                                descripcion_vecindad  \
0  [Lower Queen Anne is near the Seattle Center (...
1  [--, Capital Hill is the heart of Seattle, bor...
2  [Upper Queen Anne is a charming neighborhood f...
3  [The Views from our top floor!  Wallingford ha...
4  [Safeway grocery store within walking distance...

                                      cantidad_baños  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]
2                                                [4]
3                           [3, 3, 3, 3, 3, 3, 3, 3]
4                                             [2, 3]

                                    cantidad_cuartos  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]
2                                                [5]
3                           [6, 6, 5, 5, 5, 5, 4, 4]
4                                             [2, 6]

                                      cantidad_camas  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
1                  [5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]
2                                                [7]
3                           [6, 6, 7, 8, 7, 7, 6, 6]
4                                             [3, 9]

                                         modelo_cama  \
0  [Real Bed, Futon, Futon, Pull-out Sofa, Real B...
1  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
2                                         [Real Bed]
3  [Real Bed, Real Bed, Real Bed, Real Bed, Real ...
4                               [Real Bed, Real Bed]

                                         comodidades  \
0  [{Internet,"Wireless Internet",Kitchen,"Free P...
1  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...
2  [{TV,"Cable TV",Internet,"Wireless Internet","...
3  [{Internet,"Wireless Internet",Kitchen,"Free P...
4  [{TV,Internet,"Wireless Internet",Kitchen,"Fre...

                                      cuota_deposito  \
0  [$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...
1  [$500.00, $300.00, $0, $300.00, $300.00, $360....
2                                        [$1,000.00]
3  [$500.00, $500.00, $500.00, $500.00, $500.00, ...
4                               [$300.00, $2,000.00]

                                      cuota_limpieza  \
0  [$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...
1  [$125.00, $100.00, $85.00, $110.00, $110.00, $...
2                                          [$300.00]
3  [$225.00, $300.00, $250.00, $250.00, $250.00, ...
4                                  [$40.00, $150.00]

                                              precio
0  [$110.00, $45.00, $55.00, $52.00, $85.00, $50....
1  [$350.00, $300.00, $425.00, $300.00, $285.00, ...
2                                          [$975.00]
3  [$490.00, $550.00, $350.00, $350.00, $350.00, ...
4                                 [$200.00, $545.00]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB
None

In [ ]:
import pandas as pd
import json

# Cargar los datos originales
datos = pd.read_json('/content/datos_hosting.json')

# Normalizar la columna 'info_inmuebles'
try:
    info_inmuebles_aplanado = pd.json_normalize(datos['info_inmuebles'])
except Exception as e:
    print(f"No se pudo normalizar la columna 'info_inmuebles': {e}")
    info_inmuebles_aplanado = pd.DataFrame() # Crea un DataFrame vacío si falla

# Concatenar el DataFrame original (sin 'info_inmuebles') con el normalizado
datos_aplanado = datos.drop(columns=['info_inmuebles'], errors='ignore').copy()

if not info_inmuebles_aplanado.empty:
    datos_aplanado = pd.concat([datos_aplanado, info_inmuebles_aplanado], axis=1)
else:
    print("La normalización de 'info_inmuebles' falló o resultó vacía.")

# --- Procesar las columnas que todavía contienen listas ---

# Función para procesar columnas de descripción (tomar el primer elemento)
def get_first_element(lista):
    if isinstance(lista, list) and lista:
        return lista[0]
    return None # O alguna otra representación para valores faltantes/vacíos

# Aplicar la función a las columnas de descripción
for col in ['descripcion_local', 'descripcion_vecindad']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_element)

# Función para procesar columnas de cantidad (tomar el primer elemento)
def get_first_number(lista):
    if isinstance(lista, list) and lista:
        try:
            # Intenta convertir a número si es posible
            return float(lista[0])
        except (ValueError, TypeError):
            return None # Retorna None si no se puede convertir a número
    return None

# Aplicar la función a las columnas de cantidad
for col in ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']:
     if col in datos_aplanado.columns:
        # Intenta convertir los elementos de la lista a string antes de aplicar get_first_number
        datos_aplanado[col] = datos_aplanado[col].apply(lambda x: [str(item) for item in x] if isinstance(x, list) else x)
        datos_aplanado[col] = datos_aplanado[col].apply(get_first_number)


# Procesar 'modelo_cama' (tomar el primer elemento)
if 'modelo_cama' in datos_aplanado.columns:
    datos_aplanado['modelo_cama'] = datos_aplanado['modelo_cama'].apply(get_first_element)

# Procesar 'comodidades' (extraer las comodidades de la lista)
# Esto es más complejo y dependerá del formato exacto dentro de la lista.
# Aquí un ejemplo simple que intenta extraer elementos si son strings.
def extract_amenities(lista):
    if isinstance(lista, list):
        # Une los elementos de la lista con una coma (ajusta si necesitas algo diferente)
        return ', '.join([str(item).strip() for item in lista if isinstance(item, (str, dict, list))])
    return None

if 'comodidades' in datos_aplanado.columns:
     datos_aplanado['comodidades'] = datos_aplanado['comodidades'].apply(extract_amenities)


# Función para limpiar y convertir columnas de precio/cuota a numérico
def clean_currency(lista):
    if isinstance(lista, list) and lista:
        # Tomar el primer elemento, quitar '$' y ',' y convertir a float
        try:
            value_str = str(lista[0]).replace('$', '').replace(',', '').strip()
            if value_str: # Asegurarse de que no esté vacío después de limpiar
                 return float(value_str)
            return 0.0 # O np.nan si prefieres representar valores faltantes
        except (ValueError, TypeError):
             return 0.0 # Retornar 0.0 o np.nan si falla la conversión
    return 0.0 # Retornar 0.0 o np.nan para listas vacías o no listas

# Aplicar la función a las columnas de precio/cuota
for col in ['cuota_deposito', 'cuota_limpieza', 'precio']:
    if col in datos_aplanado.columns:
        datos_aplanado[col] = datos_aplanado[col].apply(clean_currency)

# Mostrar las primeras filas del DataFrame aplanado
print(datos_aplanado.head())

# Mostrar la información del DataFrame aplanado
print(datos_aplanado.info())

  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  This clean and comfortable one bedroom sits ri...
1  Welcome to the heart of the 'Ballard Brewery D...
2  New modern house built in 2013.  Spectacular s...
3  Our NW style home is 3200+ sq ft with 3 levels...
4  Perfect for groups. 2 bedrooms, full bathrooms...

                                descripcion_vecindad  cantidad_baños  \
0  Lower Queen Anne is near the Seattle Center (s...             1.0
1                                                 --             2.0
2  Upper Queen Anne is a charming neighborhood fu...             4.0
3  The Views from our top floor!  Wallingford has...             3.0
4  Safeway grocery store within walking distance....             2.0

   cantidad_cuartos  cantidad_camas modelo_cama  \
0               1.0             1.0    Real Bed
1               3.0             5.0    Real Bed
2               5.0             7.0    Real Bed
3               6.0             6.0    Real Bed
4               2.0             3.0    Real Bed

                                         comodidades  cuota_deposito  \
0  {Internet,"Wireless Internet",Kitchen,"Free Pa...             0.0
1  {TV,Internet,"Wireless Internet",Kitchen,"Free...           500.0
2  {TV,"Cable TV",Internet,"Wireless Internet","A...          1000.0
3  {Internet,"Wireless Internet",Kitchen,"Free Pa...           500.0
4  {TV,Internet,"Wireless Internet",Kitchen,"Free...           300.0

   cuota_limpieza  precio
0             0.0   110.0
1           125.0   350.0
2           300.0   975.0
3           225.0   490.0
4            40.0   200.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     float64
 6   cantidad_cuartos      70 non-null     float64
 7   cantidad_camas        70 non-null     float64
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     float64
 11  cuota_limpieza        70 non-null     float64
 12  precio                70 non-null     float64
dtypes: float64(6), object(7)
memory usage: 7.2+ KB
None

In [ ]:
datos_aplanado.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1.0,1.0,1.0,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,10,Welcome to the heart of the 'Ballard Brewery D...,--,2.0,3.0,5.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",500.0,125.0,350.0
2,10.0,--,11,New modern house built in 2013. Spectacular s...,Upper Queen Anne is a charming neighborhood fu...,4.0,5.0,7.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",1000.0,300.0,975.0
3,10.0,--,12,Our NW style home is 3200+ sq ft with 3 levels...,The Views from our top floor! Wallingford has...,3.0,6.0,6.0,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",500.0,225.0,490.0
4,10.0,--,14,"Perfect for groups. 2 bedrooms, full bathrooms...",Safeway grocery store within walking distance....,2.0,2.0,3.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",300.0,40.0,200.0

In [ ]:
# prompt: Mediante el marco de datos datos_aplanado: aplanar comodidades

import pandas as pd
# Split the 'comodidades' column into individual amenities and create dummy variables
comodidades_dummies = datos_aplanado['comodidades'].str.get_dummies(sep=',')
# Concatenate the new dummy variables with the original dataframe
datos_aplanado = pd.concat([datos_aplanado, comodidades_dummies], axis=1)
# Drop the original 'comodidades' column
datos_aplanado = datos_aplanado.drop('comodidades', axis=1)

In [ ]:
# --- Limpiar los nombres de las columnas ---

# Crear un diccionario para mapear nombres antiguos a nombres nuevos
column_mapping = {}
for col in datos_aplanado.columns:
    # Eliminar caracteres específicos del nombre de la columna
    new_col = col.replace('"', '').replace('{', '').replace('}', '')
    # Opcional: Puedes añadir más lógica de limpieza aquí si encuentras otros caracteres
    # Por ejemplo, eliminar espacios al principio o final: .strip()
    # new_col = new_col.strip()

    # Si el nuevo nombre es diferente al antiguo, agregarlo al mapeo
    if new_col != col:
        column_mapping[col] = new_col

# Renombrar las columnas usando el diccionario de mapeo
# El método rename solo renombra las columnas presentes en el diccionario
datos_aplanado = datos_aplanado.rename(columns=column_mapping)

# Mostrar los nuevos nombres de las columnas para verificar
print("Nuevos nombres de columnas:")
print(datos_aplanado.columns.tolist())

# Mostrar las primeras filas del DataFrame con los nombres limpios
print(datos_aplanado.head())

Nuevos nombres de columnas:
['evaluacion_general', 'experiencia_local', 'max_hospedes', 'descripcion_local', 'descripcion_vecindad', 'cantidad_baños', 'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'cuota_deposito', 'cuota_limpieza', 'precio', ' Air Conditioning', ' Cable TV', ' Elevator in Building', ' Free Parking on Premises', ' Smoke Detector', ' Wheelchair Accessible', ' Wireless Internet', ' Internet', ' Kitchen', ' Kitchen', ' Pool', ' TV', ' ', '24-Hour Check-in', '24-Hour Check-in', 'Air Conditioning', 'Buzzer/Wireless Intercom', 'Cable TV', 'Carbon Monoxide Detector', 'Carbon Monoxide Detector', 'Elevator in Building', 'Elevator in Building', 'Family/Kid Friendly', 'Family/Kid Friendly', 'Fire Extinguisher', 'Fire Extinguisher', 'First Aid Kit', 'First Aid Kit', 'Free Parking on Premises', 'Hair Dryer', 'Hair Dryer', 'Hot Tub', 'Indoor Fireplace', 'Indoor Fireplace', 'Laptop Friendly Workspace', 'Lock on Bedroom Door', 'Lock on Bedroom Door', 'Other pet(s)', 'Pets Allowed', 'Pets live on this property', 'Safety Card', 'Safety Card', 'Smoke Detector', 'Smoke Detector', 'Smoking Allowed', 'Suitable for Events', 'Suitable for Events', 'Washer / Dryer', 'Wheelchair Accessible', 'Wireless Internet', 'Wireless Internet', 'Breakfast', 'Cat(s)', 'Dog(s)', 'Doorman', 'Dryer', 'Dryer', 'Essentials', 'Essentials', 'Gym', 'Hangers', 'Hangers', 'Heating', 'Heating', 'Internet', 'Iron', 'Iron', 'Kitchen', 'Kitchen', 'Pool', 'Shampoo', 'Shampoo', 'Washer', 'Washer', 'Cable TV', 'Wireless Internet', 'Internet', 'TV']
  evaluacion_general experiencia_local max_hospedes  \
0               10.0                --            1
1               10.0                --           10
2               10.0                --           11
3               10.0                --           12
4               10.0                --           14

                                   descripcion_local  \
0  This clean and comfortable one bedroom sits ri...
1  Welcome to the heart of the 'Ballard Brewery D...
2  New modern house built in 2013.  Spectacular s...
3  Our NW style home is 3200+ sq ft with 3 levels...
4  Perfect for groups. 2 bedrooms, full bathrooms...

                                descripcion_vecindad  cantidad_baños  \
0  Lower Queen Anne is near the Seattle Center (s...             1.0
1                                                 --             2.0
2  Upper Queen Anne is a charming neighborhood fu...             4.0
3  The Views from our top floor!  Wallingford has...             3.0
4  Safeway grocery store within walking distance....             2.0

   cantidad_cuartos  cantidad_camas modelo_cama  cuota_deposito  ...  Kitchen  \
0               1.0             1.0    Real Bed             0.0  ...        0
1               3.0             5.0    Real Bed           500.0  ...        0
2               5.0             7.0    Real Bed          1000.0  ...        0
3               6.0             6.0    Real Bed           500.0  ...        0
4               2.0             3.0    Real Bed           300.0  ...        0

   Pool  Shampoo  Shampoo  Washer  Washer  Cable TV  Wireless Internet  \
0     1        1        1       1       0         0                  0
1     1        1        1       1       0         0                  0
2     0        0        1       1       0         0                  0
3     0        0        1       1       0         0                  0
4     0        0        1       1       0         0                  0

   Internet  TV
0         1   0
1         0   1
2         0   1
3         1   0
4         0   1

[5 rows x 90 columns]

In [ ]:
datos_aplanado.head(5)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,cuota_deposito,...,Kitchen,Pool,Shampoo,Shampoo,Washer,Washer,Cable TV,Wireless Internet,Internet,TV
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1.0,1.0,1.0,Real Bed,0.0,...,0,1,1,1,1,0,0,0,1,0
1,10.0,--,10,Welcome to the heart of the 'Ballard Brewery D...,--,2.0,3.0,5.0,Real Bed,500.0,...,0,1,1,1,1,0,0,0,0,1
2,10.0,--,11,New modern house built in 2013. Spectacular s...,Upper Queen Anne is a charming neighborhood fu...,4.0,5.0,7.0,Real Bed,1000.0,...,0,0,0,1,1,0,0,0,0,1
3,10.0,--,12,Our NW style home is 3200+ sq ft with 3 levels...,The Views from our top floor! Wallingford has...,3.0,6.0,6.0,Real Bed,500.0,...,0,0,0,1,1,0,0,0,1,0
4,10.0,--,14,"Perfect for groups. 2 bedrooms, full bathrooms...",Safeway grocery store within walking distance....,2.0,2.0,3.0,Real Bed,300.0,...,0,0,0,1,1,0,0,0,0,1

In [ ]:
# Obtener la lista de nombres de columnas
nombres_columnas = datos_aplanado.columns.tolist()

# Imprimir la lista de nombres de columnas
print("Nombres de las columnas en datos_aplanado:")
print(nombres_columnas)

# Opcional: Imprimir la cantidad de columnas para confirmar que son 90
print("\nCantidad de columnas:", len(nombres_columnas))

Nombres de las columnas en datos_aplanado:
['evaluacion_general', 'experiencia_local', 'max_hospedes', 'descripcion_local', 'descripcion_vecindad', 'cantidad_baños', 'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'cuota_deposito', 'cuota_limpieza', 'precio', ' Air Conditioning', ' Cable TV', ' Elevator in Building', ' Free Parking on Premises', ' Smoke Detector', ' Wheelchair Accessible', ' Wireless Internet', ' Internet', ' Kitchen', ' Kitchen', ' Pool', ' TV', ' ', '24-Hour Check-in', '24-Hour Check-in', 'Air Conditioning', 'Buzzer/Wireless Intercom', 'Cable TV', 'Carbon Monoxide Detector', 'Carbon Monoxide Detector', 'Elevator in Building', 'Elevator in Building', 'Family/Kid Friendly', 'Family/Kid Friendly', 'Fire Extinguisher', 'Fire Extinguisher', 'First Aid Kit', 'First Aid Kit', 'Free Parking on Premises', 'Hair Dryer', 'Hair Dryer', 'Hot Tub', 'Indoor Fireplace', 'Indoor Fireplace', 'Laptop Friendly Workspace', 'Lock on Bedroom Door', 'Lock on Bedroom Door', 'Other pet(s)', 'Pets Allowed', 'Pets live on this property', 'Safety Card', 'Safety Card', 'Smoke Detector', 'Smoke Detector', 'Smoking Allowed', 'Suitable for Events', 'Suitable for Events', 'Washer / Dryer', 'Wheelchair Accessible', 'Wireless Internet', 'Wireless Internet', 'Breakfast', 'Cat(s)', 'Dog(s)', 'Doorman', 'Dryer', 'Dryer', 'Essentials', 'Essentials', 'Gym', 'Hangers', 'Hangers', 'Heating', 'Heating', 'Internet', 'Iron', 'Iron', 'Kitchen', 'Kitchen', 'Pool', 'Shampoo', 'Shampoo', 'Washer', 'Washer', 'Cable TV', 'Wireless Internet', 'Internet', 'TV']

Cantidad de columnas: 90

#**Empieza el curso**

In [1]:
import pandas as pd

# Cargar los datos originales
datos = pd.read_json('https://raw.githubusercontent.com/TAGARA-TECH/Pandas_transformacion_y_manipulacion_de_datos/refs/heads/main/datos_hosting.json')

In [2]:
datos

                                       info_inmuebles
0   {'evaluacion_general': '10.0', 'experiencia_lo...
1   {'evaluacion_general': '10.0', 'experiencia_lo...
2   {'evaluacion_general': '10.0', 'experiencia_lo...
3   {'evaluacion_general': '10.0', 'experiencia_lo...
4   {'evaluacion_general': '10.0', 'experiencia_lo...
..                                                ...
65  {'evaluacion_general': 'nan', 'experiencia_loc...
66  {'evaluacion_general': 'nan', 'experiencia_loc...
67  {'evaluacion_general': 'nan', 'experiencia_loc...
68  {'evaluacion_general': 'nan', 'experiencia_loc...
69  {'evaluacion_general': 'nan', 'experiencia_loc...

[70 rows x 1 columns]

In [3]:
import pandas as pd
import json

# Cargar los datos originales nuevamente
datos = pd.read_json('https://raw.githubusercontent.com/TAGARA-TECH/Pandas_transformacion_y_manipulacion_de_datos/refs/heads/main/datos_hosting.json')

# Ahora normalizar la columna 'info_inmuebles'
datos = pd.json_normalize(datos['info_inmuebles'])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

In [4]:
# yo-> columnas = list(datos.columns)
columnas = datos.columns.tolist() #curso (son iguales)
print(columnas)
len(columnas)

['evaluacion_general', 'experiencia_local', 'max_hospedes', 'descripcion_local', 'descripcion_vecindad', 'cantidad_baños', 'cantidad_cuartos', 'cantidad_camas', 'modelo_cama', 'comodidades', 'cuota_deposito', 'cuota_limpieza', 'precio']

13

In [5]:

datos = datos.explode(columnas[3:])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [6]:
datos.reset_index(drop=True, inplace=True)
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [7]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [8]:
import numpy as np

In [9]:
datos['max_hospedes'] = datos['max_hospedes'].astype(np.int64)
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [10]:
col_numericas = ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']

In [11]:
datos[col_numericas] = datos[col_numericas].astype(np.int64)
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [12]:
datos['evaluacion_general'] = datos['evaluacion_general'].astype(np.float64)
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [13]:
#datos['precio'] = datos['precio'].astype(np.float64)
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [14]:
#datos['precio'].apply(lambda x: x.replace('$', '').replace(',', '')).astype(np.float64)
datos['precio'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

0       110.00
1        45.00
2        55.00
3        52.00
4        85.00
         ...
3813    299.00
3814    199.00
3815    400.00
3816    250.00
3817    350.00
Name: precio, Length: 3818, dtype: object

In [15]:
import pandas as pd
import numpy as np

# Suponiendo que el DataFrame 'datos' ya está cargado y procesado hasta este punto

# Limpiar la columna 'precio' eliminando '$' y ',' y eliminando espacios en blanco
datos['precio'] = datos['precio'].apply(lambda x: str(x).replace('$', '').replace(',', '').strip())
# ver tema applymap en vez de apply min4.50  curso 2.08
# Ahora, convierte los valores de cadena limpiados a float64
# Asegúrate de que la limpieza anterior tuvo éxito y no hay valores no convertibles
datos['precio'] = datos['precio'].astype(np.float64)

datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [16]:
datos[['cuota_deposito', 'cuota_limpieza']]

     cuota_deposito cuota_limpieza
0                $0             $0
1                $0             $0
2                $0             $0
3                $0         $20.00
4                $0         $15.00
...             ...            ...
3813      $1,000.00        $178.00
3814             $0         $99.00
3815             $0             $0
3816      $1,000.00        $150.00
3817        $500.00             $0

[3818 rows x 2 columns]

##**Datos de Texto**

In [17]:
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0

In [18]:
#Tokenizacion simple Tokenizacion es la divicion del texto en token, en unidades mas pequeñas. Separaremos por palabras.
datos['descripcion_local'] = datos['descripcion_local'].str.lower()

In [19]:
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,very lovely and cozy room for one. convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,the “studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0

In [20]:
datos['descripcion_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [21]:
# Limpiar la columna 'descripcion_local' eliminando caracteres que no son alfanuméricos o guiones
# Corregir el patrón de la expresión regular para cerrar correctamente el set de caracteres
datos['descripcion_local'] = datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\-]', ' ', regex=True)

# Puedes verificar el resultado en un ejemplo
print(datos['descripcion_local'][3169])

built  run and supported by seattle tech and start up veterans  grokhome s focus is to create a supportive environment for smart people working on interesting projects  start ups and more  this listing is an upper bunk  in a 2-person shared room   note  this fall  there will be major renovations happening on one kitchen and bathroom at a time  there will always be two other working kitchens and two working bathrooms in the house  we ll work to minimize the impact these renovations have on your stay    this listing is only available to those working in the tech science space  live in a hacker house  and immerse yourself in the seattle tech scene  you can expect to be surrounded by smart people solving big problems or working on something fun  we have frequent demo nights  and love when our guests share something they are passionate about  if you re new to the city  our deep ties to the seattle tech scene can help you get involved  expand your network  develop your ideas  and learn somet

In [22]:
# borrar guiones que no tengan un caracter a la derecha o a la izquierda
# Usamos (?<!\w)-(?!\w) para encontrar guiones que no están rodeados por caracteres de palabra.
# Reemplazamos esos guiones con un espacio.
datos['descripcion_local'] = datos['descripcion_local'].str.replace(r'(?<!\w)-(?!\w)', ' ', regex=True)

datos['descripcion_local'].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one  convenientl...
4    the  studio at mibbett hollow  is in a beautif...
Name: descripcion_local, dtype: object

In [23]:
datos['descripcion_local'] = datos['descripcion_local'].str.split()
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow, is, in, a, ...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0